### ISSUE TITLE
[Feat]:  Introducing Follower Profile Preview Feature

### ISSUE THREAD

**Issue by shikhar-4739** [c2siorg/Codelabz#113]
**Is your feature request related to a problem? Please describe.**
Currently, when users navigate to their "Who To Follow" list, they are unable to obtain any information about individual followers beyond their username or profile picture. This lack of information can make it challenging for users to decide whether to follow someone back or engage with them further.

**Describe the solution you'd like**
 The proposed feature aims to address this problem by enabling users to access basic information about a follower before deciding to follow them. This additional information can help users make more informed decisions and foster better engagement within the platform.

**Describe alternatives you've considered**
Similar to the proposed solution, implement a profile preview popup/modal that appears when clicking on a follower's name or profile picture. This provides a snapshot of basic information without fully navigating away from the followers list.

**Additional context**
Image:
![Screenshot 2024-02-28 154124](https://github.com/c2siorg/Codelabz/assets/135845175/00d73865-c8fe-4392-81c1-3cc6ab29a589)

**Comment by Chamara00** [comment]
@shikhar-4739 can you assign this to me?
