### ISSUE TITLE
Pre-GSoC Tasks 2024

### ISSUE THREAD

**Issue by shivareddy6** [c2siorg/Codelabz#115]
The following are Pre-GSoC tasks for 2024

## Task 1:
Design a Notifications Service System for Codelabz

### Objective:
Design a robust system for the Notification Service for Codelabz, ensuring effective communication of necessary actions and events to users.

### Tasks:  
* Document an Entity-Relationship (ER) Model based on the existing database model.
* Create an Architecture/System Flow Diagram illustrating the notification system's workings.

## Task 2:
Design a recommendation service to Generate User Feed

### Objective:
Design a basic and robust recommendation system to generate user feed for Codelabz, suggesting relevant codelabzs (tutorials) to users.

### Tasks:  
* Design a recommendation service to populate user home feeds with recommended codelabzs (tutorials).
* Document an Architecture/System Flow Diagram depicting the recommendation system's structure.
* Show How the ranking system will work, and explain the integration and working of the recommendation model.
* Contributors can add code snippets.

### Objective:
To assess contributors' implementation skills and coding practices, candidates are requested to fork the project repository and solve specified tasks. This method prevents PR flooding on the main repository and ensures confidentiality of contributors' solutions.

### Procedure:
1. Fork the repository.
2. Resolve/Implement the designated tasks.
3. Raise PRs to your forked repository.
4. Include PR links in your proposal.

### Github Task 1 :
* Like/Dislike Feature Implementation:
* Implement database interactions for user likes and dislikes.
* Implement them for tutorials and comments.
* Ensure the feature aligns with the existing database design.

### Github Task 2: 
* Add Image Feature for tutorials:
* Users currently cannot upload images while creating tutorials
* Fix this issue to upload images in tutorial.

### Github Task 3: 
* Fix Bugs in Tutorials comments 
* Comments are not shown when posted, needs to be reloaded to view the comment.

### Note:
**Kindly refrain from submitting PRs to the main repository, as these tasks are not intended for merging into the main codebase. Your contributions should be confined to your forked repository for evaluation purposes.**

**Comment by siddanth-6365** [comment]
@shivareddy6 ( sorry for tagging)
 can I work on task 1 by creating an ER model or anyone else working on it?

**Comment by ishanguptaofficial** [comment]
Hi can you assign this task to me ? I want to work in this issue.

**Comment by Aditya-Sakpal** [comment]
> Hi can you assign this task to me ? I want to work in this issue.

Hey @ishanguptaofficial  these are tasks related to GSOC selections . You have to make the prs in your own cloned repo and mention them in your proposal . Hope this helps :)
