### ISSUE TITLE
Footer enhancement

### ISSUE THREAD

**Issue by Apurv428** [c2siorg/Codelabz#118]
**Describe the bug**

The footer lacks visual appeal, appearing crumpled and improperly formatted. There are underlines present due to anchor tags, and spacing is not adequately maintained.

**To Reproduce**

(As footer is commented in the code, I viewed it using storybook. So first we need to do : `npm run storybook`)

1. Go to 'Home section' in left sidebar
2. Click on 'Footer'

**Expected behavior**

Enhancement of the footer by maintaining the same design while improving overall formatting for a more polished and cohesive appearance.

**Screenshots**

![image](https://github.com/c2siorg/Codelabz/assets/84929607/f0b01505-9187-4b08-adc7-c4b9999cb362)

Proposed Design:

![image](https://github.com/c2siorg/Codelabz/assets/84929607/4e5e3787-37df-4cd9-b13a-3fda697d8ae7)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Brave

**Comment by ishanguptaofficial** [comment]
Hi can you assign this task to me ? I want to work in this issue.
