### ISSUE TITLE
Website link is not relevant

### ISSUE THREAD

**Issue by TheNourhan** [c2siorg/Codelabz#120]
**Describe the bug**
When you click on the site link on the README file `https://dev.codelabz.io/`, a wrong site appears

**To Reproduce**

1. Go to 'README.md'
2. Click on 'Deployment link'

**Screenshots**
<img width="904" alt="Screenshot 2024-03-10 184321" src="https://github.com/c2siorg/Codelabz/assets/109472010/e2537469-f81f-40c0-8c70-eb881eb56d7a">

**Comment by ishanguptaofficial** [comment]
Hi can you assign this task to me ? I want to work in this issue.

**Comment by TheNourhan** [comment]
You can do PR
