### ISSUE TITLE
change Twitter to X

### ISSUE THREAD

**Issue by TheNourhan** [c2siorg/Codelabz#122]
**Describe the bug**
Twitter does not exist anymore, so all Twitter icons must be changed to X

**Comment by ishanguptaofficial** [comment]
Hi can you assign this task to me ? I want to work in this issue.

**Comment by ShivendraTrivedi** [comment]
Hey @TheNourhan can you assign this task to me as it just needed to change the svg icon of twitter into X with the same file name, which will automatically change the icon everywhere without individually changing the icon everywhere in the code.

**Comment by TheNourhan** [comment]
You can do PR

**Comment by ishanguptaofficial** [comment]
Hey,
all Pr is already created, I want to do this project I can create a
proposal for this, I have a good experience in full stack including 3 year
of work experience as well in company.

please give me a chance and accept my proposal for this project in GOSC
2024.

Thank You
