### ISSUE TITLE
Addressing Negative and Unlimited Voting Behavior in Upvote/Downvote System

### ISSUE THREAD

**Issue by soham2312** [c2siorg/Codelabz#133]
**Describe the bug**
Users can cast negative votes and unlimited upvotes/downvotes within the upvote/downvote system, contrary to the intended behavior. This issue compromises data integrity and may lead to system abuse.

**To Reproduce**

Go to any post.
Click on the upvote/downvote button multiple times.
Observe negative voting counts or unlimited voting behavior.

**Expected behavior**
The voting system should prevent users from casting negative votes and limit the number of upvotes/downvotes to one to maintain data integrity and prevent abuse.

**Desktop & Smartphone**

OS: all OS
Browser: all Browser
Version: all Version

**Additional context**
This issue impacts the reliability and fairness of the voting system and requires immediate attention to maintain the integrity of user feedback data.

**Comment by rohitPandey469** [comment]
@soham2312  Please refrain from creating already tackled issues
