### ISSUE TITLE
Creating dynamic content in organisation section in profile page

### ISSUE THREAD

**Issue by Shubh942** [c2siorg/Codelabz#17]
**Is your feature request related to a problem? Please describe.**
Content is static in the organisation section on the profile page

**Describe the solution you'd like**
We can fetch the data from the Firebase database

**Describe alternatives you've considered**
using organisation array in database can be rendered dynamically
![image](https://github.com/c2siorg/Codelabz/assets/93862397/269f9b1f-8e60-4985-8bfb-45caaac7905a)

**Additional context**
![image](https://github.com/c2siorg/Codelabz/assets/93862397/8b170cb8-368c-47a5-8c05-96573e64336a)

**Comment by Huzaif-Ahmed** [comment]
Hi shubh i would like to work on this issue can you please assign it to me
