### ISSUE TITLE
Organization Page Fails to Load

### ISSUE THREAD

**Issue by anudeeps0306** [c2siorg/Codelabz#24]
**Describe the bug**
When attempting to open the organization page using the URL pattern /org/${url}, the page fails to load

**Expected behavior**
The organization page should load successfully when navigating to the URL /org/${url}.

**Screenshots**

![Screenshot from 2024-01-27 14-49-59](https://github.com/c2siorg/Codelabz/assets/71971574/93d73ebf-f598-45ff-b813-81874142d599)

**Comment by Aditya-Sakpal** [comment]
This issue is been raised multiple times in the previous repo
