### ISSUE TITLE
User not being redirected to the specific organization's page 

### ISSUE THREAD

**Issue by Aditya-Sakpal** [c2siorg/Codelabz#3]
**Describe the bug**
User not being redirected to the specific organization's page where he/she should see organization's details

**To Reproduce**

1.Go to dashboard 
2.Enter user and organization's details and hit save
3.Now on dashboard/my_feed page click on the organization's banner

**Expected behavior**
User should be redirected to that org's page

**Video Reference**

https://github.com/c2siorg/Codelabz/assets/112710558/33398aac-5783-4a37-adc4-7638273320b7

**Comment by AnmolSirola** [comment]
@Aditya-Sakpal Can I take this issue.

**Comment by Hemu21** [comment]
@Aditya-Sakpal Can I solve This Issue. @ABHISHEK-PANDEY2 @Maahi10001 @Shiva-Nanda /assign-me

**Comment by Aditya-Sakpal** [comment]
@Hemu21 @AnmolSirola  I'm not the maintainer bro :). I'm just a fellow contributor.
