### ISSUE TITLE
Update README: Replace Old Communication Channels with New Ones

### ISSUE THREAD

**Issue by AnmolSirola** [c2siorg/Codelabz#5]
**Is your feature request related to a problem? Please describe.**

The current README for CodeLabz contains information about an outdated communication channel, namely the Glitter channel. This poses a challenge for new contributors who may attempt to join the deprecated channel instead of the current primary communication platform, which is the Slack channel.

**Describe the solution you'd like**

The purpose of this issue is to update the README, replacing references to the old Glitter channel with accurate details about the current Slack channel. This will streamline the onboarding process for new contributors and ensure they have the correct information to join the community.

**Comment by Hemu21** [comment]
I updated the readme file communication channel with new ones
