### ISSUE TITLE
[ Fix : Creating Organization is Not Fully Integrated ]

### ISSUE THREAD

**Issue by rohitPandey469** [c2siorg/Codelabz#74]
**Describe the bug**
If a user log in or signup with his own account, then user would need to create an organization too to create tutorials, so after creating organization as prompted when visited to view the organization, it kept on loading suggesting somewhere the data needed for the page to load is not provided or missing i.e. it's kept on waiting for the data to come, or something similar.

**To Reproduce**

1. Log In with your own account.
2. You will be prompted to create an organization. Do so.
3. Visit the Organization through sidebar.
4. Page kept on loading.
5.  Try creating a tutorial - it won't work aswell.

**Expected behavior**
It should have shown organizations general section when visited to `http://localhost:5173/org/settings/org_handle`

**Video**
In black screen instance of chrome logged in with the account and created an organization then tried to view it - which is not showing 
In tutorial creation there is no options for tutorials.
White screen shows how it should have been worked.

https://github.com/c2siorg/Codelabz/assets/123815256/5a7c2a34-7aa6-4712-8590-39bebb6f3adc

https://github.com/c2siorg/Codelabz/assets/123815256/37f0376e-4135-4d46-8d5a-bd7defedbdc3

All in all, a user can not create his own organization.
**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome

**Additional context**
Do suggest outcomes or possible errors which needed to be fixed in order to make it work.

**Comment by rohitPandey469** [comment]
Thanks @Aditya-Sakpal for mentioning else I would have used up my time solving it

**Comment by rohitPandey469** [comment]
Closing it

**Comment by rohitPandey469** [comment]
@Aditya-Sakpal, Are you sure that this issue have been solved, it ain't working when I copied the changes

**Comment by Aditya-Sakpal** [comment]
The issue has already been raised and few guys have already created prs for this , including myself . Like this is my pr :- https://github.com/c2siorg/Codelabz/pull/4 . In this pr there are many unnecessary files changes (I'll change it later won't take much time)
