### ISSUE TITLE
adding sharing option for tutorials

### ISSUE THREAD

**Issue by sudheerdagar** [c2siorg/Codelabz#75]
**Problem:**
Users often want to share tutorials they find helpful with others, but there's currently no straightforward way to do so on the web-based frontend.

**Solution:**
Implement a sharing option for tutorials on the web-based frontend. This would involve adding a "Share" button underneath each tutorial, allowing users to easily share the tutorial link via various platforms such as email, social media, or messaging apps.

**Alternatives:**
1. Manually copying and pasting the tutorial link to share it.
2. Implementing social media sharing plugins or widgets for each tutorial page.
3. Adding a "Share via Email" option where users can input email addresses to send the tutorial link directly.

**Additional Context:**
This feature would enhance user experience by promoting easier sharing of valuable content, fostering community engagement, and potentially attracting more users to the platform through word-of-mouth recommendations.

**Comment by Huzaif-Ahmed** [comment]
i have also implemented this in october on scorelab's repo
