### ISSUE TITLE
[ Feat : Dynamic Content In 'Who To Follow' Section at Home Page ]

### ISSUE THREAD

**Issue by rohitPandey469** [c2siorg/Codelabz#82]
**Is your feature request related to a problem? Please describe.**
Here, the data is fixed aswell
![image](https://github.com/c2siorg/Codelabz/assets/123815256/3812df6b-a8dc-4f98-99fb-ddd5ebb4b181)
So will be loading dynamic data here as well.

**Describe the solution you'd Implement**
Loading the owner's of all the organization present under codelabz. This is what currently I am thinking to do.

**Describe alternatives you've considered**
1. Load Users with most followers. ( Well the issue with follow btn is already solved - so will be good to do this )
2. Or, have a field called interest in user doc and do a survey when creating user or user can edit his interests later on as well, then filter users based on the interest.
3. Can do 'Personalized Recommendations' using ML algorithms - it will be quite troublesome though.

**Additional context**
Do share your ideas.

**Comment by shikhar-4739** [comment]
hey @rohitPandey469 i am also working on this issue.
