### ISSUE TITLE
Social Media Icon Buttons are not Working

### ISSUE THREAD

**Issue by Hemu21** [c2siorg/Codelabz#88]
**Describe the bug**
Social Media Icon Buttons are not Working properly in profile page. while clicking on them they are not redirecting to the particular path. 

**To Reproduce**

1. Set-up the project in your localhost.
2. Now run and go to the profile page.
3. You find icons of facebook, github,linkedin etc.
4. click on them they are not redirecting before clicking make sure that you have provided the user profile name in the user settings path for that social media.

https://github.com/c2siorg/Codelabz/assets/106808387/f16d204b-1bff-45e6-8cc7-7ae278fa6f24

**Expected behavior**

while clicking on them they should redirect to the particular path. I mean user profile.

**Comment by rohitPandey469** [comment]
@Hemu21 Nice work, but this one is already solved brother i.e. storing the data at profile settings and then populating the social icons with it and redirecting.
But if you did it in some different way like something more cool or wild make sure to mention it, here in the threads or in the PR explicitly.

**Comment by rohitPandey469** [comment]
@Hemu21 You can create multiple PR for the same issue if you feel like more than one solution would be expected for that one in particular. You would know by looking at the issue, cause they want the best solution.
But for this one it's a no no

**Comment by Hemu21** [comment]
ok I am closing.
